package com.nagarro.jenkins.plugin.exceptions;

/**
 * This exception will occurr, whenever Jenkins seed job will unable to connect SVN due to authentication or other reasons
 * @author saurabh01
 *
 */
public class JenkinsSeedJobFailException extends Exception{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public JenkinsSeedJobFailException(Exception exception) {
		super(exception);
	}

	public JenkinsSeedJobFailException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public JenkinsSeedJobFailException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO Auto-generated constructor stub
	}

	public JenkinsSeedJobFailException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public JenkinsSeedJobFailException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}
	
}
